import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/app.scss";
import { cookies } from "next/headers";
import AppThemeProvider from "@/components/context/Theme";
import Navbar from "@/components/Navbar";
import TopBar from "@/components/TopBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = (await cookies()).get("__theme__")?.value || "dark";

  return (
    <html lang="en" suppressHydrationWarning className={theme}>
      <body>
        <AppThemeProvider attribute="class" defaultTheme={theme} enableSystem>
          <TopBar />
          {children}
          <Navbar />
        </AppThemeProvider>
      </body>
    </html>
  );
}
