import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/app.scss";
import Navbar from "@/components/Navbar";
import TopBar from "@/components/global/TopBar";
import ServiceWorker from "@/components/ServiceWorker";

export const metadata: Metadata = {
  title: "LoveU Festival App",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <TopBar />
      <main className={"grow flex flex-col"}>{children}</main>
      <Navbar />
      <ServiceWorker />
    </>
  );
}
