name: Run ESLint and TSC tests

on:
  push:
    branches: [master, main]
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile
      - run: bun run lint
      - run: bun run test

      - run: bunx tsc

      - run: bun run build

      - name: "Create env file"
        run: |
          touch .env
          echo "DATABASE_URL=${DATABASE_URL}" >> .env
          echo "NEXT_PUBLIC_VAPID_PUBLIC_KEY=${NEXT_PUBLIC_VAPID_PUBLIC_KEY}" >> .env
          echo "VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}" >> .env

          cat .env
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_VAPID_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_VAPID_PUBLIC_KEY }}
          VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}

      - name: Sync build to remote
        if: ${{ success() }}
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: .next/
          remote_path: ${{ secrets.PROJECT_PATH }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Reload pm2
        if: ${{ success() }}
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            export BUN_INSTALL="$HOME/.bun"
            export PATH="$BUN_INSTALL/bin:$PATH"
            echo "Bun Version: $(bun --version)"
            source ~/.nvm/nvm.sh
            cd ..
            git pull
            bun i

            bunx drizzle-kit migrate

            pm2 restart ecosystem.config.js
