name: Run ESLint and TSC tests

on:
  push:
    branches: [development]
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - name: "Create env file"
        run: |
          touch .env
          echo "DATABASE_URL=${DATABASE_URL}" >> .env
          echo "NEXT_PUBLIC_VAPID_PUBLIC_KEY=${NEXT_PUBLIC_VAPID_PUBLIC_KEY}" >> .env
          echo "VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}" >> .env
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_VAPID_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_VAPID_PUBLIC_KEY }}
          VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}

      - run: bun run lint
      - run: bun run test

      - run: bunx tsc
